Part 2
DariaPikul/CinemaTickets pull request #1
Opened 2020-09-30 15:05 UTC by DariaPikul

2020-09-30 15:17 UTC, frostpv commented on src/main/java/com/dev/cinema/dao/implementation/MovieDaoImplementation.java
> +            session = HibernateUtil.getSessionFactory().openSession();
трай с ресурсами

2020-09-30 15:17 UTC, frostpv commented on src/main/java/com/dev/cinema/dao/implementation/MovieDaoImplementation.java
> +            session = HibernateUtil.getSessionFactory().openSession();
трай с ресурсами

2020-09-30 15:17 UTC, andromash requested changes
Masterpiece!

2020-09-30 15:17 UTC, andromash commented on src/main/java/com/dev/cinema/dao/implementation/MovieDaoImplementation.java
> +            movie.setId(id);
we don't need to set it manually, Hibernate does it by itself

2020-09-30 15:17 UTC, andromash commented on src/main/java/com/dev/cinema/dao/GenericDao.java
> +public interface GenericDao<T> {
Not sure we need to create it in this hw

2020-09-30 15:17 UTC, andromash commented on src/main/java/com/dev/cinema/dao/implementation/MovieDaoImplementation.java
> +            }
In this case, we don't use transaction so you can put session to resources block

2020-09-30 15:17 UTC, andromash commented on src/main/java/com/dev/cinema/exceptions/DataBaseDataExchangeException.java
> +    public DataBaseDataExchangeException(String message, Throwable cause) {
not sure if this name of the exception is informative

2020-09-30 15:17 UTC, andromash commented on src/main/java/com/dev/cinema/model/Movie.java
> +public class Movie {
In this case, Hibernate will create a table "Movie" but it is not the best practice to name the table with the first letter in the Upper case. You can use an annotation Table with parameter name

2020-09-30 15:19 UTC, DariaPikul commented on src/main/java/com/dev/cinema/dao/implementation/MovieDaoImplementation.java
> +            session = HibernateUtil.getSessionFactory().openSession();
Didn't work with such construction

2020-09-30 15:41 UTC, andromash approved these changes
Incredible! Amazing! 10 out of 10!

2020-09-30 17:04 UTC, dmytro-hryhoruk commented on pom.xml
> +    </dependencies>
let's move dependencies after properties

2020-09-30 17:04 UTC, dmytro-hryhoruk commented on src/main/java/com/dev/cinema/dao/implementation/MovieDaoImplementation.java
> +public class MovieDaoImplementation implements MovieDao {
```suggestion
public class MovieDaoImpl implements MovieDao {
```
More than enough)

2020-10-01 09:17 UTC, dmytro-hryhoruk approved these changes

2020-10-01 11:25 UTC, merged