Part - 9
DariaPikul/CinemaTickets pull request #10
Opened 2020-10-22 15:43 UTC by DariiaPikul

- **Dao and Service** : method get(Long id) created
- **Controllers** : Authentication, Movie, and MovieSession created
- **Models** : DTO's created

2020-10-22 15:55 UTC, andromash reviewed
Nice!

2020-10-22 15:55 UTC, andromash commented on src/main/java/com/dev/cinema/controller/AuthenticationController.java
> +            throw new RegistrationException("The passwords should be equal");
not sure we need to throw an exception here. We should pass a message to the client. Anyway, we will use annotation for this purpose in the future homework

2020-10-22 15:55 UTC, andromash commented on src/main/java/com/dev/cinema/controller/MovieController.java
> +                .map(MovieMapper::mapToResponseDto)
did you make these methods static? maybe it would be better to inject object and use non-static methods

2020-10-22 15:55 UTC, andromash commented on src/main/java/com/dev/cinema/controller/MovieSessionController.java
> +@RequestMapping("/movie_sessions")
```suggestion
@RequestMapping("/movie-sessions")
```

2020-10-23 07:23 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/controller/AuthenticationController.java
> +@RequestMapping
do we need this annotation here?

2020-10-23 07:23 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/controller/AuthenticationController.java
> +        if (!userDto.getPassword().equals(userDto.getRepeatedPassword())) {
we will complete validation later on, let's remove it for now

2020-10-23 07:23 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/controller/MovieController.java
> +    @PostMapping("/")
```suggestion
    @PostMapping
```

2020-10-23 07:23 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/controller/MovieSessionController.java
> +    @PostMapping("/")
same

2020-10-23 07:23 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/model/dto/MovieDto.java
> +public class MovieDto {
Request and Response dtos should be different 
we don't wanna to except id in request, it should be generated by db

2020-10-23 07:23 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/model/dto/MovieSessionDto.java
> +public class MovieSessionDto {
same here

2020-10-23 07:23 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/model/dto/UserDto.java
> +public class UserDto {
same here

2020-10-23 07:23 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/controller/MovieSessionController.java
> +            @RequestParam Long movieId, @RequestParam String date) {
you may user this approach as well
@RequestParam @DateTimeFormat(pattern = "dd.MM.yyyy") LocalDate date

2020-10-23 07:23 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/service/mapper/UserMapper.java
> +public class UserMapper {
we don't need UserMapper now, let's remove it

2020-10-23 13:55 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/model/dto/UserResponseDto.java
> +    private String repeatedPassword;
do we need this field now, if not let's add code when we need it

2020-10-23 13:55 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/controller/AuthenticationController.java
> +    public void register(@RequestBody UserResponseDto userResponseDto) {
it's requestDto not response

2020-10-26 10:00 UTC, KseniiaMakarova requested changes

2020-10-26 10:00 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/UserRequestDto.java
>      private Long id;
let's remove this field as well

2020-10-26 10:00 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/UserRequestDto.java
> +    public UserRequestDto(Long id, String email, String password) {
are you using this constructor?

2020-10-26 10:04 UTC, KseniiaMakarova requested changes

2020-10-26 10:04 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieRequestDto.java
> +    }
same
are you creating this object anywhere?

2020-10-26 10:04 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/MovieSessionRequestDto.java
> +    }
same

2020-10-26 10:54 UTC, KseniiaMakarova approved these changes

2020-10-26 10:57 UTC, merged